### PR TITLE
Added the checkout page

### PR DESCRIPTION
**Pull request by Predcodes69**
1. This PR fixes or fixes part of #10 
2. This PR does the following: Added the checkout page with the appropriate responsiveness and in accordance with the given design
3. It includes a form component, which will be subdivided into sub-components in a upcoming PR.

## Proof that changes are correct
Mobile View:
image
image
image
Tablet View:
image
image

Desktop View;
image

Any constructive reviews are welcomed. PTAL @Priyansh61 @thejaysharma @tushitshukla03

### CODE REVIEW

**Comment by Predcodes69** [comment]
Also, the borders arent visible in the screenshots but they are there, and they are visible enough

**Comment by Priyansh61** [comment]
@Predcodes69 Please update it with the upstream I dont know your deploy preview is not working?

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
In the mobile view, the website should be aligned in the center, and the comment box should occupy the entire width as shown in the Figma design. Additionally, the input boxes should be in a square shape.

@Predcodes69

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
Please add a placeholder in the inputs.

**Comment by Priyansh61** [comment]
@Predcodes69 Any updates?

**Comment by Predcodes69** [comment]
Hello @Priyansh61 @prernadabi23 I made the requested changes, please review.

**Comment by prernadabi23** [comment]
@Predcodes69 Solve the linting errors.

**Comment by Predcodes69** [comment]
> @Predcodes69 Solve the linting errors.
Can you please elaborate where are the linting errors here? A screenshot would help. Thanks.

**Comment by Predcodes69** [comment]
@prernadabi23 PTAL, I made an attempt at solving the linting errors.

**Pull request closed without merging**
