### PR TITLE
feat: add to Cart

### PR DESCRIPTION
**Pull request by AkashPaloju**
## Overview

1. This PR fixes or fixes part of #90 .
2. This PR does the following: makes the 'Add to Cart' and 'Remove from cart(Cross X)' button functional.  The Cart page now displays the items added to the cart by the user by retrieving data from Vuex store. The Vuex store is persisted across browser refreshes/sessions as it is saved in the local storage of the browser. The User is notified about adding/removing products through informative "toasts".

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/GetIt/assets/119884665/81c0edea-c130-4771-a187-a15461501db4

## PR Pointers

@tushitshukla03  PTAL, please let  me know if any further adjustments are required

### CODE REVIEW

**Comment by tushitshukla03** [comment]
@AkashPaloju First sync your branch and implement + - feature of cart and also make the heading and text in cart fixed at top. Change the toast position to bottom center and also make it square.

**Comment by AkashPaloju** [comment]
@tushitshukla03 someone removed the product heading in the product page, is it requested by the maintainers or removed accidentally? should i add the title which was like earlier or leave it

image

**Comment by tushitshukla03** [comment]
> @tushitshukla03 someone removed the product heading in the product page, is it requested by the maintainers or removed accidentally? should i add the title which was like earlier or leave it
> 
> image
>  

No it was removed as the title in the mobile view was two times.

**Comment by AkashPaloju** [comment]
@tushitshukla03 I am closing this PR since I have some issues with the current branch. I am opening a new PR

**Pull request closed without merging**
