### PR TITLE
#202 :feat(index_page): create components for events and merchandise cards

### PR DESCRIPTION
**Pull request by ANIRUDHNARANG0**
## Overview

1. This PR fixes or fixes part of #198   .
2. This PR does the following: create a event and merch card

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/GetIt/assets/149250431/a8fe1a74-a371-4099-b516-d05263fa2abf

button shadow

box shadow animation

https://github.com/bsoc-bitbyte/GetIt/assets/149250431/93a58d58-ff25-49aa-b702-c9d0ebc29fa7

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Review by Kushdapush — CHANGES_REQUESTED** [review]
Great work @ANIRUDHNARANG0 
Now we want to display only 3 events and 3 products so please figure out a way to "GetIt" done!

**Comment by ANIRUDHNARANG0** [comment]
@Kushdapush I have made the required chnages

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju i have removed extra poppins from styles

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju i have made the required changes

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju  i have added routing feature for traversing

**Comment by ANIRUDHNARANG0** [comment]
@AkashPaloju  i have made changes and have used nuxt link for routing

**Review by Kushdapush — APPROVED** [review]

**Pull request merged**
