### PR TITLE
Navbar using Tailwind CSS

### PR DESCRIPTION
**Pull request by rrtk857**
## Overview

1. This PR fixes or fixes part of #15.
2. This PR does the following: Navbar with Tailwind CSS

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by prernadabi23** [comment]
@rrtk857, please attempt to resolve the lint errors.

**Comment by rrtk857** [comment]
@prernadabi23, I have tried to remove lint errors. Please review it.
Also corrected issue #28.

**Comment by prernadabi23** [comment]
@rrtk857 Please rebase your pull request.

**Comment by prernadabi23** [comment]
@rrtk857 Is there any issue?

**Review by thejaysharma — CHANGES_REQUESTED** [review]
Resolve the conflicts and try to make a PR which solves the particular issue only.

**Comment by rrtk857** [comment]
@thejaysharma, I will try to resolve the conflicts.

**Pull request closed without merging**
