### PR TITLE
refactor: incorporated tailwindcss in signin and signup page

### PR DESCRIPTION
**Pull request by Predcodes69**
## Overview

1. This PR fixes or fixes part of #7 
2. This PR does the following: Incorporated  Tailwindcss into the code, made some logical fixes,  and some responsiveness hassles

## Proof that changes are correct
Mobile view of Signup Page
image
Mobile view of Signin Page
image
Desktop View of Signup page
image
Desktop view of Signin page
image

##Review
Any constructive reviews are welcomed, @arminpatel @thejaysharma @Priyansh61 @tushitshukla03 @JawHawk

### CODE REVIEW

**Review by thejaysharma — CHANGES_REQUESTED** [review]
Hello, @Predcodes69 Pages' margins appear to be inadequate for mobile viewing. Additionally, add extra padding to the input fields (and placeholders).

**Comment by thejaysharma** [comment]
@Predcodes69, For your reference, look at the figma file.

**Comment by Predcodes69** [comment]
> @Predcodes69 the sign-up and sign-in text should be changed to white.

@prernadabi23 in this code, the sign in and sign up text changes to white on hover, However, I will make the changes.

**Comment by Priyansh61** [comment]
@Predcodes69 Do we need this PR? Or can you close this one?

**Pull request closed without merging**
