### PR TITLE
Integrated fronTend with backend

### PR DESCRIPTION
**Pull request by tushitshukla03**
## Overview

1. This PR fixes or fixes part of #[N/A].

3. This PR does the following: [This Pr made the eventlist dynamic on home page. Integrated frontend with backend.Made the specific page for the event and reintegrated the cart as per ticket]

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Priyansh61** [comment]
image
image

Image alligment needs to be fixed!

**Comment by Priyansh61** [comment]
- checkout functionality is not working, like after adding to cart the checkout doesnt show the price of the item you added to the cart.
- There should also be a buy now button along with this because currently only add to cart is visible.
- Something wrong with the image ratio at the event list page
image
- This section looks a bit odd currently, Ig some UI changes needs to be done here
image
- The cart logic is not working correclty, this needs to be fixed. IG..

**Comment by Priyansh61** [comment]
@tushitshukla03 PTAL!

**Review by arminpatel — COMMENTED** [review]
The cart is functioning properly.

**Comment by Priyansh61** [comment]
@tushitshukla03 Almost everything looks but can you please once check the image ratio either they get distorted or either their ratio becomes unusually.

And like on the EventList page can you change the event ratio so that the images looks great. After this we can merge the PR.

**Comment by Priyansh61** [comment]
@tushitshukla03 Can we improve this layout?

image

**Comment by tushitshukla03** [comment]
> @tushitshukla03 Can we improve this layout? And why are we getting `by 3`
> 
> image

fixed the image size

**Review by Priyansh61 — COMMENTED** [review]
LGTM! @arminpatel PTAL. and check the `auth.js` once.

Also @tushitshukla03 can you remove the `backend/core/media/event_cover_image` from the PR. Thanks !!

**Review by Priyansh61 — APPROVED** [review]

**Comment by Priyansh61** [comment]
@arminpatel check and merge the PR

**Review by arminpatel — APPROVED** [review]
LGTM

**Pull request merged**
