### PR TITLE
made the shop page 

### PR DESCRIPTION
**Pull request by Kushdapush**
## Overview

1. This PR fixes or fixes part of #76 .
2. This PR does the following: made the functional shop page 

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/GetIt/assets/129064700/087b0f0e-a903-4191-b748-1bf5fd542ee2

### CODE REVIEW

**Comment by Kushdapush** [comment]
@tushitshukla03 PTAL

**Review by tushitshukla03 — CHANGES_REQUESTED** [review]
@Kushdapush the shop page is not centered and there is no back button in filters.
give some space between products. In mobile view the page loads with a zoom.

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
Make two products shown in the mobile view, and the filters option should be sticky on the left side. When it is opened, it should take up the entire screen, just like any other e-commerce website for the mobile view. 

WhatsApp Image 2023-07-23 at 20 27 23

**Comment by prernadabi23** [comment]
Any Updates? @Kushdapush

**Review by thejaysharma — COMMENTED** [review]
@Kushdapush any updates?
Make the required changes as soon as possible. Also resolve the conflicts.

**Pull request closed without merging**
