### PR TITLE
made the requested changes

### LINKED ISSUE #78: [BUG]:  Fix the product page
### Describe the bug

Fixing some ui of product page to make them look alike to figma design.
Using the font and colour of the figma design. Fix the spacing between button.
Make the colour selector functional.

### Steps To Reproduce

_No response_

### Expected Behavior

_No response_

### Screenshots/Videos

_No response_

### What device are you using?

_No response_

### Operating System

_No response_

### What browsers are you seeing the problem on?

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shramanpaul**
## Overview

1. This PR fixes or fixes part of #78 .
2. This PR does the following: [Fixed the UI of product page to make them look alike the figma design.
changed the font and color of the radio button. Fixed the spacing between the buttons.
Made the color selector functional.

## Essential Checklist

- [x] The PR title starts with "Fix #78 "
- [x] "Allow edits from maintainers" is checked.
- [x] The PR is made from a branch that's  called "changes".

## Proof that changes are correct

WhatsApp Image 2023-07-14 at 23 30 29

## PR Pointers

@tushitshukla03  PTAL

### CODE REVIEW

**Comment by tushitshukla03** [comment]
@shramanpaul color selection still not working

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/GetIt/assets/110323017/20c32170-e943-415d-8da5-67cc7a0f9034

@tushitshukla03  it is working on my local machine PTAL

**Comment by shramanpaul** [comment]
made the changes as requested @tushitshukla03  PTAL

**Review by thejaysharma — APPROVED** [review]
LGTM! @shramanpaul Great work. :)

**Comment by tushitshukla03** [comment]
@shramanpaul color selection is once again misplaced is mobile view. It was at correct position in main.

**Comment by shramanpaul** [comment]
@tushitshukla03  I have made the changes PTAL.

**Review by tushitshukla03 — APPROVED** [review]

**Pull request merged**
