### PR TITLE
Fix #161: Added auto-versioning feature

### LINKED ISSUE #161: [Feature Request]: Add Version Release history in the project
### Is your feature request related to a problem? Please describe.

No 

### Describe the solution you'd like

Would love to have a version history for the project with a changelog of what all changes and which version the project is currently running at?

### Describe alternatives you've considered

_No response_

### Developer Help

https://www.youtube.com/watch?v=BbdFfvZNWNw

You can reference this video for understanding what actually we want with the project.

### PR DESCRIPTION
**Pull request by Adi8712**
## Overview

1. This PR fixes or fixes part of #161.
2. This PR does the following: uses github actions to automate version bumps and generate changelog

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

Screenshot from 2024-04-18 18-30-38

### CODE REVIEW

**Comment by Adi8712** [comment]
@arminpatel @Priyansh61 PTAL

**Review by Priyansh61 — APPROVED** [review]
LGTM

**Review by arminpatel — CHANGES_REQUESTED** [review]
@Adi8712 please update the changelog

**Comment by Adi8712** [comment]
@arminpatel PTAL

**Review by arminpatel — APPROVED** [review]

**Pull request merged**
