### PR TITLE
build : Added build.py to setup the backend and incorporated a global .gitignore

### PR DESCRIPTION
**Pull request by Priyansh61**
## Overview

1. This PR fixes or fixes part of #40
2. This PR does the following: Single build.py to setup the local env setup

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Comment by Priyansh61** [comment]
@arminpatel Dont merge it because the scripts are being executed in global env instead of venv if you think of any way do let me know

**Comment by Priyansh61** [comment]
@arminpatel @Tusharjain123  Any suggestions?

**Comment by arminpatel** [comment]
@Priyansh61 imo using python to use a subprocess to source a file would be difficult and really roundabout way to do it. How about using a simple shell script. Or rather doing this at some later stage?

**Comment by Tusharjain123** [comment]
@Priyansh61 I will prefer using a shell script because using a subprocess in Python to source a file will be a bit complex as compared to a shell script. With shell script, we can directly execute the source command to load the environment variables.

**Comment by Priyansh61** [comment]
@arminpatel @Tusharjain123 Your suggestion really helped! Take a look now and just check if the venv gets activated correctly now because we dont want to mess things up, since there will be a lot of dependecies in the near future else they will be installed globally

**Review by arminpatel — APPROVED** [review]

**Pull request merged**
