### PR TITLE
Fix #161 - make releases easily

### LINKED ISSUE #161: [Feature Request]: Add Version Release history in the project
### Is your feature request related to a problem? Please describe.

No 

### Describe the solution you'd like

Would love to have a version history for the project with a changelog of what all changes and which version the project is currently running at?

### Describe alternatives you've considered

_No response_

### Developer Help

https://www.youtube.com/watch?v=BbdFfvZNWNw

You can reference this video for understanding what actually we want with the project.

### PR DESCRIPTION
**Pull request by Adi8712**
## Overview

1. This PR fixes #161 .
2. This PR does the following: Uses release-it to setup a more developer-friendly method to make releases and updates changelog.md file automatically

## Proof that changes are correct

Screenshot from 2024-04-15 15-34-12

### CODE REVIEW

**Comment by Priyansh61** [comment]
@Adi8712 SInce generally we are after the release so shouldnt it be > v1.0.0 ?

**Comment by Adi8712** [comment]
There's been no release as of yet so I assumed we'll test it and then ahead with release v1

**Comment by Adi8712** [comment]
@Priyansh61 I have set the version to 1.0.1 and emptied the changelog.md file
Use npm run release and it should work

**Review by arminpatel — COMMENTED** [review]
@Adi8712 how about a GitHub action instead of a npm package?

**Comment by Adi8712** [comment]
@arminpatel The way I planned it after seeing the issue is using release-it as a dedicated tool for handling releases and in future automating release-it using GitHub actions.
Although GitHub actions can help automate literally anything using a dedicated tool for releases seems more flexible and easier I guess.

**Comment by arminpatel** [comment]
> @arminpatel The way I planned it after seeing the issue is using release-it as a dedicated tool for handling releases and in future automating release-it using GitHub actions.
> Although GitHub actions can help automate literally anything using a dedicated tool for releases seems more flexible and easier I guess.

The way I see it, assuming both methods provide the same functionality, using actions would remove unnecessary code from the project, save extra setup steps for the user.

@Priyansh61 wdyt?

**Comment by Priyansh61** [comment]
> > @arminpatel The way I planned it after seeing the issue is using release-it as a dedicated tool for handling releases and in future automating release-it using GitHub actions.
> > Although GitHub actions can help automate literally anything using a dedicated tool for releases seems more flexible and easier I guess.
> 
> The way I see it, assuming both methods provide the same functionality, using actions would remove unnecessary code from the project, save extra setup steps for the contributors.
> 
> @Priyansh61 wdyt?

Yup!! Ig @arminpatel pointed out the right thing it would be better to get more things off from the local setup and try to get things more in automation.. So I believe using GH actions would be much better.

**Comment by Adi8712** [comment]
@Priyansh61 @arminpatel I looked into it and found [GH Release](https://github.com/marketplace/actions/gh-release).
I guess this'll do, my only question is how do I take care of the GitHub token, I can set it up for my fork but someone has to do it for this repo as well I guess.

**Pull request closed without merging**
