### PR TITLE
Added the Cart component

### PR DESCRIPTION
**Pull request by Kushdapush**
## Overview

1. This PR fixes or fixes part of #31 .
2. This PR does the following: Added the Cart component according to the design provided and added relevant files for the same objective

## Essential Checklist

- [ x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

image

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Review by thejaysharma — CHANGES_REQUESTED** [review]
cart figma
cart

See the difference between figma design and your page.
1.  Too much gap between products.
2.   Product Price and Number of quantities should have different colour.
3.   Subtotal, Discount section should be same as shown in figma design. 
4.   Try to make your page responsive.

You can verify the colour in the figma file. Go to a quick tutorial for utilising figma if you don't know how to use it.

**Comment by Kushdapush** [comment]
@thejaysharma Sir i have made the requested changes in the PR , will you PTAL

**Comment by Kushdapush** [comment]
image
@prernadabi23  @thejaysharma  @tushitshukla03 please tell me if any more changes are required

**Comment by Kushdapush** [comment]
The prices are not yet shown because i think that the task of adding them should be done when making the cart functional in order to make it less complicated
if you want then ill add them as well

**Comment by tushitshukla03** [comment]
@Kushdapush just lighten the bg of + -  and allign them at center

**Review by tushitshukla03 — APPROVED** [review]

**Pull request merged**
