### PR TITLE
fix: Corrected the dimensions of images.

### PR DESCRIPTION
**Pull request by Doraemon012**
## Overview

1. This PR fixes or fixes part of #26
2. This PR does the following: 
  - Corrected the dimensions of the product image and the images in the slider.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

### CODE REVIEW

**Comment by prernadabi23** [comment]
Screenshot from 2023-07-11 23-36-08

9 commits behind @Doraemon012

**Comment by Doraemon012** [comment]
@prernadabi23 I have resolved all the conflicts.
Now, my branch is 2 commits ahead of GetIt/main.

**Comment by prernadabi23** [comment]
@Doraemon012, there is an error in your PR. We cannot see some changes that have been merged today. Could you please check once? The buttons on the shop page have been modified, but we cannot see the changes in your PR.

**Comment by Doraemon012** [comment]
@prernadabi23 Ma'am I have resolved the problems and committed the changes. Please check it once.

**Review by prernadabi23 — APPROVED** [review]

**Pull request merged**
