### PR TITLE
Made the cart page mobile friendly.

### PR DESCRIPTION
**Pull request by prateekjha1204**
## Overview

1. This PR fixes or fixes part of #77 
2. This PR does the following: Makes the cart page mobile friendly.

## Essential Checklist

- [ ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ ] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [ ] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

Here is the Screenshot
Screenshot (32)

## PR Pointers

@tushitshukla03 PTAL

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Review by tushitshukla03 — CHANGES_REQUESTED** [review]
@prateekjha1204 give margin from left and right 
image

**Comment by prateekjha1204** [comment]
@tushitshukla03 Did the requested changes, below is the Screenshot
Screenshot (33)

**Comment by thejaysharma** [comment]
@prateekjha1204 Make the page responsive for tablets.
mobile

**Review by thejaysharma — CHANGES_REQUESTED** [review]
@prateekjha1204 Make the page responsive for tablets.
mobile

**Comment by prateekjha1204** [comment]
@thejaysharma Made the page responsive for tablets, below is the Screenshot
Screenshot (34)

**Comment by tushitshukla03** [comment]
@prateekjha1204 the illustration(image) in desktop has become too small. Please check everything is fine before making commits

**Comment by tushitshukla03** [comment]
@prateekjha1204 your  branch is behind behind main

**Comment by prateekjha1204** [comment]
@tushitshukla03 I have made the requested changes for the text of the price summary box. Font-weight of the text is 500 and the color of the price are #81858b, here's the SS
Screenshot (42)

PTAL

**Review by tushitshukla03 — APPROVED** [review]

**Pull request merged**
