### PR TITLE
feat: add to cart btn functionality

### PR DESCRIPTION
**Pull request by AkashPaloju**
## Overview

1. This PR fixes or fixes part of #90 .
2. This PR does the following: makes the 'Add to Cart' and 'Remove from cart(Cross X)',increment (+) and decrement(-) buttons functional. The Cart page now displays the items added to the cart by the user by retrieving data from Vuex store. The Vuex store is persisted across browser refreshes/sessions as it is saved in the local storage of the browser. The User is notified about adding/removing/increments/decrements of products through informative toast notifications.

## Essential Checklist

- [x] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)
- [x] The PR is made from a branch that's **not** called "main/master".

## Proof that changes are correct

https://github.com/bsoc-bitbyte/GetIt/assets/119884665/9c93d256-3d4d-41b7-b822-180a6f707d94
 
this below preview is for "storing on local storage"

https://github.com/bsoc-bitbyte/GetIt/assets/119884665/ea9cf6f6-365f-4816-bb0b-22df73d32260

## PR Pointers

@tushitshukla03 PTAL

### CODE REVIEW

**Review by tushitshukla03 — CHANGES_REQUESTED** [review]
@AkashPaloju + - in the cart section is working but not refreshing the value and don't show total price here for product, just the item price and quantity don't multiply. In mobile view the content is going out of box in cart and make heading aligned. Fix the UI and rest is good

**Comment by AkashPaloju** [comment]
https://github.com/bsoc-bitbyte/GetIt/assets/119884665/10bf6ab2-60be-4127-9599-ff43190644e2

@tushitshukla03 I have made the requested changes

**Comment by AkashPaloju** [comment]
@tushitshukla03 It is working in the latest deployment also

https://github.com/bsoc-bitbyte/GetIt/assets/119884665/f90f6cb8-4541-42a0-b921-075126601b59

**Comment by tushitshukla03** [comment]
@AkashPaloju when it is added for the first time +- is not working only after refreshing it start working. And include size also in cart and if we add product of different size or colour then add that as a new entry instead of increasing quantity and remove the limit of 5. Image is still getting cut  and in mobile view card is overflowing.

**Comment by AkashPaloju** [comment]
@tushitshukla03 made the required changes again

**Comment by AkashPaloju** [comment]
@tushitshukla03 PTAL

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
Everything looks good, but the user can access the checkout page even if the cart is empty. So, could you do something, like ensuring that the user adds a product first before being able to proceed to checkout?

**Comment by AkashPaloju** [comment]
> Everything looks good, but the user can access the checkout page even if the cart is empty. So, could you do something, like ensuring that the user adds a product first before being able to proceed to checkout?

@prernadabi23 ok, i will do the required thing

**Comment by AkashPaloju** [comment]
@prernadabi23 PTAL the latest commit
preview:

Uploading checkoutbtn.mp4…

**Review by prernadabi23 — APPROVED** [review]
Great work! Just rebase your PR.

**Comment by AkashPaloju** [comment]
@prernadabi23 i rebased it .
image

**Comment by AkashPaloju** [comment]
@prernadabi23 I rebased it, 
image

**Review by thejaysharma — APPROVED** [review]
Good Job :) @AkashPaloju

**Review by tushitshukla03 — APPROVED** [review]

**Pull request merged**
