### PR TITLE
fixed the posiiton of the buttons

### LINKED ISSUE #27: [Feature Request]: Buy Now and Add to Cart should stick at the bottom of the product page.
### Is your feature request related to a problem? Please describe.

Currently when the user scrolls down the product page the buy now and add to cart button goes up, so in order to click them the user has to go back up again to buy/add the product.

### Describe the solution you'd like

Both the buttons should stick at the bottom of the page and should have position fixed when the user scrolls the page.

### Describe alternatives you've considered

_No response_

### Developer Help

You can see the button should be similar to what flipkart uses currently.

image

### PR DESCRIPTION
**Pull request by shramanpaul**
## Overview

1. This PR fixes or fixes part of #[27].
2. This PR does the following: [fixes the position of add to cart and buy now buttons at the bottom]

## Essential Checklist

- [x] The PR title starts with "Fix #27  "
- [x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)

## Proof that changes are correct

https://github.com/bsoc-bitbyte/GetIt/assets/110323017/41a2762a-fdc2-4d74-ac51-2a657512fb61

## PR Pointers
 
@Priyansh61  PTAL

### CODE REVIEW

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/GetIt/assets/110323017/529a4b2e-3a06-4a2f-a906-06699749a1ad

@Priyansh61 PTAL

**Review by thejaysharma — DISMISSED** [review]
@shramanpaul  fix the button size for mobile as well as tablet screen.
button2
button

**Review by Priyansh61 — CHANGES_REQUESTED** [review]
@shramanpaul Also try to keep the buttons layout for mobile display similar to the flipkart one as shown in the issue description and leave the desktop display as it is.

Thanks

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/GetIt/assets/110323017/84877bd3-c201-44b4-b7be-6c46b0caf952

@Priyansh61  @thejaysharma  I have made the changes as requested PTAL.

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
In the desktop view, it is nowhere near the Figma design. Please correct it.

Screenshot from 2023-07-09 15-23-37

Please keep the buttons separate for the mobile view, as described by @Priyansh61 . I am attaching the Flipkart design again for reference.

Screenshot from 2023-07-09 15-23-44

WhatsApp Image 2023-07-09 at 15 27 38

**Comment by shramanpaul** [comment]
https://github.com/bsoc-bitbyte/GetIt/assets/110323017/64180207-db41-44ac-9bc7-8932abcb7965


@Priyansh61  @prernadabi23  @thejaysharma  made the requested changes similar to the Figma design provided
 PTAL

**Review by prernadabi23 — CHANGES_REQUESTED** [review]
The color of the "Buy Now" button should be according to the theme, specifically [EA454C].
@shramanpaul

**Comment by shramanpaul** [comment]
made the changes as requested @prernadabi23 PTAL

**Comment by tushitshukla03** [comment]
@shramanpaul both button length is not equal.
Also add to cart icon is not aligned correctly 
image


Change the icon. Icons are white not black so instead of using black icon and inverting it to white use white only as sometimes browser or tailwind dont support this.

check font size and font family should be poppins.

**Comment by shramanpaul** [comment]
@prernadabi23  the changes have been made I will be making the PR soon

**Comment by shramanpaul** [comment]
@tushitshukla03  @prernadabi23  @thejaysharma  @Priyansh61  PTAL

**Review by tushitshukla03 — APPROVED** [review]

**Comment by shramanpaul** [comment]
@tushitshukla03  PTAL

**Pull request merged**
